const WEAPON_CATALOG = [
  {
    id: 'pistol',
    label: 'Pistol',
    type: 'projectile',
    damage: 25,
    speed: 500,
    cooldown: 300,
    range: 2000,
    spread: 0,
    size: 6,
    color: '#ffcc44',
    trailColor: '#ffcc4444',
    sound: 'shoot',
    recoil: 2,
  },
  {
    id: 'shotgun',
    label: 'Shotgun',
    type: 'projectile',
    damage: 15,
    speed: 450,
    cooldown: 600,
    range: 800,
    spread: 0.25,
    pellets: 4,
    size: 5,
    color: '#ff8844',
    trailColor: '#ff884444',
    sound: 'shoot',
    recoil: 5,
  },
  {
    id: 'blaster',
    label: 'Blaster',
    type: 'projectile',
    damage: 20,
    speed: 600,
    cooldown: 250,
    range: 2000,
    spread: 0,
    size: 7,
    color: '#44ddff',
    trailColor: '#44ddff44',
    sound: 'shoot',
    recoil: 3,
    glow: true,
  },
  {
    id: 'rocket',
    label: 'Rocket Launcher',
    type: 'projectile',
    damage: 45,
    speed: 300,
    cooldown: 1200,
    range: 2000,
    spread: 0,
    size: 10,
    color: '#ff4444',
    trailColor: '#ff444444',
    sound: 'shoot',
    recoil: 6,
    splash: 60,
    smokeTrail: true,
  },
  {
    id: 'bat',
    label: 'Bat',
    type: 'melee',
    damage: 35,
    speed: 0,
    cooldown: 500,
    range: 55,
    spread: 0.8,
    size: 0,
    color: '#aa7744',
    sound: 'hit',
    recoil: 0,
    swingArc: 1.2,
  },
  {
    id: 'grenade',
    label: 'Grenade',
    type: 'projectile',
    damage: 40,
    speed: 350,
    cooldown: 1500,
    range: 1200,
    spread: 0,
    size: 8,
    color: '#44aa44',
    trailColor: '#44aa4444',
    sound: 'shoot',
    recoil: 2,
    splash: 80,
    arc: true,
  },
  {
    id: 'sniper',
    label: 'Sniper',
    type: 'projectile',
    damage: 50,
    speed: 900,
    cooldown: 1500,
    range: 3000,
    spread: 0,
    size: 4,
    color: '#ff2244',
    trailColor: '#ff224444',
    sound: 'shoot',
    recoil: 8,
  },
  {
    id: 'smg',
    label: 'SMG',
    type: 'projectile',
    damage: 10,
    speed: 550,
    cooldown: 120,
    range: 1200,
    spread: 0.08,
    size: 4,
    color: '#ffaa22',
    trailColor: '#ffaa2244',
    sound: 'shoot',
    recoil: 1,
  },
  {
    id: 'crossbow',
    label: 'Crossbow',
    type: 'projectile',
    damage: 35,
    speed: 700,
    cooldown: 900,
    range: 2500,
    spread: 0,
    size: 5,
    color: '#aa6633',
    trailColor: '#aa663344',
    sound: 'shoot',
    recoil: 4,
  },
  {
    id: 'flamethrower',
    label: 'Flamethrower',
    type: 'projectile',
    damage: 8,
    speed: 300,
    cooldown: 60,
    range: 400,
    spread: 0.15,
    pellets: 2,
    size: 8,
    color: '#ff6622',
    trailColor: '#ff662244',
    sound: 'shoot',
    recoil: 0,
  },
  {
    id: 'sword',
    label: 'Sword',
    type: 'melee',
    damage: 40,
    speed: 0,
    cooldown: 400,
    range: 65,
    spread: 0.6,
    size: 0,
    color: '#aaaacc',
    sound: 'hit',
    recoil: 0,
    swingArc: 1.4,
  },
  {
    id: 'hammer',
    label: 'Hammer',
    type: 'melee',
    damage: 55,
    speed: 0,
    cooldown: 800,
    range: 50,
    spread: 1.0,
    size: 0,
    color: '#888888',
    sound: 'hit',
    recoil: 0,
    swingArc: 1.8,
  },
]

function getWeapon(id) {
  return WEAPON_CATALOG.find(w => w.id === id) || WEAPON_CATALOG[0]
}
